/*
 * EBAD API
 * This documentation describe EBAD API.
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fr.dtrouillet.api;

import io.swagger.client.model.ApiTokenDto;
import io.swagger.client.model.ApiTokenWithKeyDto;
import io.swagger.client.model.PageApiTokenDto;
import io.swagger.client.model.Pageable;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApiTokenApi
 */
@Ignore
public class ApiTokenApiTest {

    private final ApiTokenApi api = new ApiTokenApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTokenTest() {
        ApiTokenDto body = null;
        ApiTokenWithKeyDto response = api.createToken(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTokenTest() {
        Long id = null;
        api.deleteToken(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findTokenTest() {
        Pageable pageable = null;
        PageApiTokenDto response = api.findToken(pageable);

        // TODO: test validations
    }
}
