/*
 * EBAD API
 * This documentation describe EBAD API.
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fr.dtrouillet.api;

import io.swagger.client.model.GlobalSettingKeyValueDto;
import io.swagger.client.model.GlobalSettingValueDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GlobalSettingApi
 */
@Ignore
public class GlobalSettingApiTest {

    private final GlobalSettingApi api = new GlobalSettingApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllSettingsTest() {
        List<GlobalSettingKeyValueDto> response = api.getAllSettings();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getValueTest() {
        String key = null;
        GlobalSettingKeyValueDto response = api.getValue(key);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setValueTest() {
        GlobalSettingValueDto body = null;
        String key = null;
        GlobalSettingKeyValueDto response = api.setValue(body, key);

        // TODO: test validations
    }
}
