/*
 * EBAD API
 * This documentation describe EBAD API.
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fr.dtrouillet.api;

import io.swagger.client.model.ActualiteDto;
import io.swagger.client.model.PageActualiteDto;
import io.swagger.client.model.Pageable;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NewApi
 */
@Ignore
public class NewApiTest {

    private final NewApi api = new NewApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void delete2Test() {
        Long id = null;
        api.delete2(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getActualityPublishedTest() {
        Pageable pageable = null;
        PageActualiteDto response = api.getActualityPublished(pageable);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAll2Test() {
        Pageable pageable = null;
        PageActualiteDto response = api.getAll2(pageable);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOne1Test() {
        Long id = null;
        ActualiteDto response = api.getOne1(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void save1Test() {
        ActualiteDto body = null;
        api.save1(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void update1Test() {
        ActualiteDto body = null;
        api.update1(body);

        // TODO: test validations
    }
}
