/*
 * EBAD API
 * This documentation describe EBAD API.
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fr.dtrouillet.api;

import io.swagger.client.model.CreationSchedulingDto;
import io.swagger.client.model.PageSchedulingDto;
import io.swagger.client.model.Pageable;
import io.swagger.client.model.SchedulingDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SchedulingApi
 */
@Ignore
public class SchedulingApiTest {

    private final SchedulingApi api = new SchedulingApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addSchedulingTest() {
        CreationSchedulingDto body = null;
        SchedulingDto response = api.addScheduling(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTest() {
        Long schedulingId = null;
        api.delete(schedulingId);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTest() {
        Long schedulingId = null;
        SchedulingDto response = api.get(schedulingId);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAllTest() {
        Pageable pageable = null;
        PageSchedulingDto response = api.listAll(pageable);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listByEnvironmentTest() {
        Long environmentId = null;
        Pageable pageable = null;
        PageSchedulingDto response = api.listByEnvironment(environmentId, pageable);

        // TODO: test validations
    }
}
