/*
 * EBAD API
 * This documentation describe EBAD API.
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.client.model.ApplicationSimpleDto;
import io.swagger.client.model.UserSimpleDto;
import io.swagger.v3.oas.annotations.media.Schema;
import org.joda.time.DateTime;
/**
 * AccreditationRequestDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-10T21:22:29.539Z[GMT]")
public class AccreditationRequestDto {
  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDate")
  private DateTime createdDate = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDate")
  private DateTime lastModifiedDate = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("user")
  private UserSimpleDto user = null;

  @JsonProperty("wantManage")
  private Boolean wantManage = null;

  @JsonProperty("wantUse")
  private Boolean wantUse = null;

  @JsonProperty("application")
  private ApplicationSimpleDto application = null;

  @JsonProperty("state")
  private String state = null;

  public AccreditationRequestDto createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @Schema(description = "")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public AccreditationRequestDto createdDate(DateTime createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @Schema(description = "")
  public DateTime getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(DateTime createdDate) {
    this.createdDate = createdDate;
  }

  public AccreditationRequestDto lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  @Schema(description = "")
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public AccreditationRequestDto lastModifiedDate(DateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
    return this;
  }

   /**
   * Get lastModifiedDate
   * @return lastModifiedDate
  **/
  @Schema(description = "")
  public DateTime getLastModifiedDate() {
    return lastModifiedDate;
  }

  public void setLastModifiedDate(DateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }

  public AccreditationRequestDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public AccreditationRequestDto user(UserSimpleDto user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @Schema(description = "")
  public UserSimpleDto getUser() {
    return user;
  }

  public void setUser(UserSimpleDto user) {
    this.user = user;
  }

  public AccreditationRequestDto wantManage(Boolean wantManage) {
    this.wantManage = wantManage;
    return this;
  }

   /**
   * Get wantManage
   * @return wantManage
  **/
  @Schema(required = true, description = "")
  public Boolean isWantManage() {
    return wantManage;
  }

  public void setWantManage(Boolean wantManage) {
    this.wantManage = wantManage;
  }

  public AccreditationRequestDto wantUse(Boolean wantUse) {
    this.wantUse = wantUse;
    return this;
  }

   /**
   * Get wantUse
   * @return wantUse
  **/
  @Schema(required = true, description = "")
  public Boolean isWantUse() {
    return wantUse;
  }

  public void setWantUse(Boolean wantUse) {
    this.wantUse = wantUse;
  }

  public AccreditationRequestDto application(ApplicationSimpleDto application) {
    this.application = application;
    return this;
  }

   /**
   * Get application
   * @return application
  **/
  @Schema(description = "")
  public ApplicationSimpleDto getApplication() {
    return application;
  }

  public void setApplication(ApplicationSimpleDto application) {
    this.application = application;
  }

   /**
   * Get state
   * @return state
  **/
  @Schema(description = "")
  public String getState() {
    return state;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccreditationRequestDto accreditationRequestDto = (AccreditationRequestDto) o;
    return Objects.equals(this.createdBy, accreditationRequestDto.createdBy) &&
        Objects.equals(this.createdDate, accreditationRequestDto.createdDate) &&
        Objects.equals(this.lastModifiedBy, accreditationRequestDto.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDate, accreditationRequestDto.lastModifiedDate) &&
        Objects.equals(this.id, accreditationRequestDto.id) &&
        Objects.equals(this.user, accreditationRequestDto.user) &&
        Objects.equals(this.wantManage, accreditationRequestDto.wantManage) &&
        Objects.equals(this.wantUse, accreditationRequestDto.wantUse) &&
        Objects.equals(this.application, accreditationRequestDto.application) &&
        Objects.equals(this.state, accreditationRequestDto.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdBy, createdDate, lastModifiedBy, lastModifiedDate, id, user, wantManage, wantUse, application, state);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccreditationRequestDto {\n");
    
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDate: ").append(toIndentedString(lastModifiedDate)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    wantManage: ").append(toIndentedString(wantManage)).append("\n");
    sb.append("    wantUse: ").append(toIndentedString(wantUse)).append("\n");
    sb.append("    application: ").append(toIndentedString(application)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
