/*
 * EBAD API
 * This documentation describe EBAD API.
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.client.model.Environnement;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;
/**
 * Application
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-04T22:32:11.845Z[GMT]")
public class Application {
  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDate")
  private DateTime createdDate = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDate")
  private DateTime lastModifiedDate = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("externalId")
  private String externalId = null;

  @JsonProperty("pluginId")
  private String pluginId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("code")
  private String code = null;

  @JsonProperty("dateFichierPattern")
  private String dateFichierPattern = null;

  @JsonProperty("dateParametrePattern")
  private String dateParametrePattern = null;

  @JsonProperty("environnements")
  private List<Environnement> environnements = null;

  public Application createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @Schema(required = true, description = "")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public Application createdDate(DateTime createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @Schema(required = true, description = "")
  public DateTime getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(DateTime createdDate) {
    this.createdDate = createdDate;
  }

  public Application lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  @Schema(description = "")
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public Application lastModifiedDate(DateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
    return this;
  }

   /**
   * Get lastModifiedDate
   * @return lastModifiedDate
  **/
  @Schema(description = "")
  public DateTime getLastModifiedDate() {
    return lastModifiedDate;
  }

  public void setLastModifiedDate(DateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }

  public Application id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Application externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * Get externalId
   * @return externalId
  **/
  @Schema(description = "")
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  public Application pluginId(String pluginId) {
    this.pluginId = pluginId;
    return this;
  }

   /**
   * Get pluginId
   * @return pluginId
  **/
  @Schema(description = "")
  public String getPluginId() {
    return pluginId;
  }

  public void setPluginId(String pluginId) {
    this.pluginId = pluginId;
  }

  public Application name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Application code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @Schema(required = true, description = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public Application dateFichierPattern(String dateFichierPattern) {
    this.dateFichierPattern = dateFichierPattern;
    return this;
  }

   /**
   * Get dateFichierPattern
   * @return dateFichierPattern
  **/
  @Schema(description = "")
  public String getDateFichierPattern() {
    return dateFichierPattern;
  }

  public void setDateFichierPattern(String dateFichierPattern) {
    this.dateFichierPattern = dateFichierPattern;
  }

  public Application dateParametrePattern(String dateParametrePattern) {
    this.dateParametrePattern = dateParametrePattern;
    return this;
  }

   /**
   * Get dateParametrePattern
   * @return dateParametrePattern
  **/
  @Schema(description = "")
  public String getDateParametrePattern() {
    return dateParametrePattern;
  }

  public void setDateParametrePattern(String dateParametrePattern) {
    this.dateParametrePattern = dateParametrePattern;
  }

  public Application environnements(List<Environnement> environnements) {
    this.environnements = environnements;
    return this;
  }

  public Application addEnvironnementsItem(Environnement environnementsItem) {
    if (this.environnements == null) {
      this.environnements = new ArrayList<Environnement>();
    }
    this.environnements.add(environnementsItem);
    return this;
  }

   /**
   * Get environnements
   * @return environnements
  **/
  @Schema(description = "")
  public List<Environnement> getEnvironnements() {
    return environnements;
  }

  public void setEnvironnements(List<Environnement> environnements) {
    this.environnements = environnements;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Application application = (Application) o;
    return Objects.equals(this.createdBy, application.createdBy) &&
        Objects.equals(this.createdDate, application.createdDate) &&
        Objects.equals(this.lastModifiedBy, application.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDate, application.lastModifiedDate) &&
        Objects.equals(this.id, application.id) &&
        Objects.equals(this.externalId, application.externalId) &&
        Objects.equals(this.pluginId, application.pluginId) &&
        Objects.equals(this.name, application.name) &&
        Objects.equals(this.code, application.code) &&
        Objects.equals(this.dateFichierPattern, application.dateFichierPattern) &&
        Objects.equals(this.dateParametrePattern, application.dateParametrePattern) &&
        Objects.equals(this.environnements, application.environnements);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdBy, createdDate, lastModifiedBy, lastModifiedDate, id, externalId, pluginId, name, code, dateFichierPattern, dateParametrePattern, environnements);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Application {\n");
    
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDate: ").append(toIndentedString(lastModifiedDate)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    pluginId: ").append(toIndentedString(pluginId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    dateFichierPattern: ").append(toIndentedString(dateFichierPattern)).append("\n");
    sb.append("    dateParametrePattern: ").append(toIndentedString(dateParametrePattern)).append("\n");
    sb.append("    environnements: ").append(toIndentedString(environnements)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
