/*
 * EBAD API
 * This documentation describe EBAD API.
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * AuthorityApplicationDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-04T22:32:11.845Z[GMT]")
public class AuthorityApplicationDTO {
  @JsonProperty("loginUser")
  private String loginUser = null;

  @JsonProperty("addModo")
  private Boolean addModo = null;

  @JsonProperty("addUser")
  private Boolean addUser = null;

  @JsonProperty("removeUser")
  private Boolean removeUser = null;

  @JsonProperty("removeModo")
  private Boolean removeModo = null;

  @JsonProperty("idApplication")
  private Long idApplication = null;

  public AuthorityApplicationDTO loginUser(String loginUser) {
    this.loginUser = loginUser;
    return this;
  }

   /**
   * Get loginUser
   * @return loginUser
  **/
  @Schema(description = "")
  public String getLoginUser() {
    return loginUser;
  }

  public void setLoginUser(String loginUser) {
    this.loginUser = loginUser;
  }

  public AuthorityApplicationDTO addModo(Boolean addModo) {
    this.addModo = addModo;
    return this;
  }

   /**
   * Get addModo
   * @return addModo
  **/
  @Schema(description = "")
  public Boolean isAddModo() {
    return addModo;
  }

  public void setAddModo(Boolean addModo) {
    this.addModo = addModo;
  }

  public AuthorityApplicationDTO addUser(Boolean addUser) {
    this.addUser = addUser;
    return this;
  }

   /**
   * Get addUser
   * @return addUser
  **/
  @Schema(description = "")
  public Boolean isAddUser() {
    return addUser;
  }

  public void setAddUser(Boolean addUser) {
    this.addUser = addUser;
  }

  public AuthorityApplicationDTO removeUser(Boolean removeUser) {
    this.removeUser = removeUser;
    return this;
  }

   /**
   * Get removeUser
   * @return removeUser
  **/
  @Schema(description = "")
  public Boolean isRemoveUser() {
    return removeUser;
  }

  public void setRemoveUser(Boolean removeUser) {
    this.removeUser = removeUser;
  }

  public AuthorityApplicationDTO removeModo(Boolean removeModo) {
    this.removeModo = removeModo;
    return this;
  }

   /**
   * Get removeModo
   * @return removeModo
  **/
  @Schema(description = "")
  public Boolean isRemoveModo() {
    return removeModo;
  }

  public void setRemoveModo(Boolean removeModo) {
    this.removeModo = removeModo;
  }

  public AuthorityApplicationDTO idApplication(Long idApplication) {
    this.idApplication = idApplication;
    return this;
  }

   /**
   * Get idApplication
   * @return idApplication
  **/
  @Schema(description = "")
  public Long getIdApplication() {
    return idApplication;
  }

  public void setIdApplication(Long idApplication) {
    this.idApplication = idApplication;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorityApplicationDTO authorityApplicationDTO = (AuthorityApplicationDTO) o;
    return Objects.equals(this.loginUser, authorityApplicationDTO.loginUser) &&
        Objects.equals(this.addModo, authorityApplicationDTO.addModo) &&
        Objects.equals(this.addUser, authorityApplicationDTO.addUser) &&
        Objects.equals(this.removeUser, authorityApplicationDTO.removeUser) &&
        Objects.equals(this.removeModo, authorityApplicationDTO.removeModo) &&
        Objects.equals(this.idApplication, authorityApplicationDTO.idApplication);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loginUser, addModo, addUser, removeUser, removeModo, idApplication);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorityApplicationDTO {\n");
    
    sb.append("    loginUser: ").append(toIndentedString(loginUser)).append("\n");
    sb.append("    addModo: ").append(toIndentedString(addModo)).append("\n");
    sb.append("    addUser: ").append(toIndentedString(addUser)).append("\n");
    sb.append("    removeUser: ").append(toIndentedString(removeUser)).append("\n");
    sb.append("    removeModo: ").append(toIndentedString(removeModo)).append("\n");
    sb.append("    idApplication: ").append(toIndentedString(idApplication)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
