/*
 * EBAD API
 * This documentation describe EBAD API.
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.client.model.ChaineAssociationBatchDto;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ChaineAssociationDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-04T22:32:11.845Z[GMT]")
public class ChaineAssociationDto {
  @JsonProperty("batchOrder")
  private Integer batchOrder = null;

  @JsonProperty("batch")
  private ChaineAssociationBatchDto batch = null;

  public ChaineAssociationDto batchOrder(Integer batchOrder) {
    this.batchOrder = batchOrder;
    return this;
  }

   /**
   * Get batchOrder
   * @return batchOrder
  **/
  @Schema(description = "")
  public Integer getBatchOrder() {
    return batchOrder;
  }

  public void setBatchOrder(Integer batchOrder) {
    this.batchOrder = batchOrder;
  }

  public ChaineAssociationDto batch(ChaineAssociationBatchDto batch) {
    this.batch = batch;
    return this;
  }

   /**
   * Get batch
   * @return batch
  **/
  @Schema(description = "")
  public ChaineAssociationBatchDto getBatch() {
    return batch;
  }

  public void setBatch(ChaineAssociationBatchDto batch) {
    this.batch = batch;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChaineAssociationDto chaineAssociationDto = (ChaineAssociationDto) o;
    return Objects.equals(this.batchOrder, chaineAssociationDto.batchOrder) &&
        Objects.equals(this.batch, chaineAssociationDto.batch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(batchOrder, batch);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChaineAssociationDto {\n");
    
    sb.append("    batchOrder: ").append(toIndentedString(batchOrder)).append("\n");
    sb.append("    batch: ").append(toIndentedString(batch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
