/*
 * EBAD API
 * This documentation describe EBAD API.
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.client.model.BatchEnvironnementDto;
import io.swagger.client.model.ChaineAssociationDto;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;
/**
 * ChaineDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-04T22:32:11.845Z[GMT]")
public class ChaineDto {
  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDate")
  private DateTime createdDate = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDate")
  private DateTime lastModifiedDate = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("chaineAssociations")
  private List<ChaineAssociationDto> chaineAssociations = null;

  @JsonProperty("environnement")
  private BatchEnvironnementDto environnement = null;

  public ChaineDto createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @Schema(description = "")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public ChaineDto createdDate(DateTime createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @Schema(description = "")
  public DateTime getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(DateTime createdDate) {
    this.createdDate = createdDate;
  }

  public ChaineDto lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  @Schema(description = "")
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public ChaineDto lastModifiedDate(DateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
    return this;
  }

   /**
   * Get lastModifiedDate
   * @return lastModifiedDate
  **/
  @Schema(description = "")
  public DateTime getLastModifiedDate() {
    return lastModifiedDate;
  }

  public void setLastModifiedDate(DateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }

  public ChaineDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ChaineDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ChaineDto description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ChaineDto chaineAssociations(List<ChaineAssociationDto> chaineAssociations) {
    this.chaineAssociations = chaineAssociations;
    return this;
  }

  public ChaineDto addChaineAssociationsItem(ChaineAssociationDto chaineAssociationsItem) {
    if (this.chaineAssociations == null) {
      this.chaineAssociations = new ArrayList<ChaineAssociationDto>();
    }
    this.chaineAssociations.add(chaineAssociationsItem);
    return this;
  }

   /**
   * Get chaineAssociations
   * @return chaineAssociations
  **/
  @Schema(description = "")
  public List<ChaineAssociationDto> getChaineAssociations() {
    return chaineAssociations;
  }

  public void setChaineAssociations(List<ChaineAssociationDto> chaineAssociations) {
    this.chaineAssociations = chaineAssociations;
  }

  public ChaineDto environnement(BatchEnvironnementDto environnement) {
    this.environnement = environnement;
    return this;
  }

   /**
   * Get environnement
   * @return environnement
  **/
  @Schema(description = "")
  public BatchEnvironnementDto getEnvironnement() {
    return environnement;
  }

  public void setEnvironnement(BatchEnvironnementDto environnement) {
    this.environnement = environnement;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChaineDto chaineDto = (ChaineDto) o;
    return Objects.equals(this.createdBy, chaineDto.createdBy) &&
        Objects.equals(this.createdDate, chaineDto.createdDate) &&
        Objects.equals(this.lastModifiedBy, chaineDto.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDate, chaineDto.lastModifiedDate) &&
        Objects.equals(this.id, chaineDto.id) &&
        Objects.equals(this.name, chaineDto.name) &&
        Objects.equals(this.description, chaineDto.description) &&
        Objects.equals(this.chaineAssociations, chaineDto.chaineAssociations) &&
        Objects.equals(this.environnement, chaineDto.environnement);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdBy, createdDate, lastModifiedBy, lastModifiedDate, id, name, description, chaineAssociations, environnement);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChaineDto {\n");
    
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDate: ").append(toIndentedString(lastModifiedDate)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    chaineAssociations: ").append(toIndentedString(chaineAssociations)).append("\n");
    sb.append("    environnement: ").append(toIndentedString(environnement)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
