/*
 * EBAD API
 * This documentation describe EBAD API.
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.client.model.NormeDto;
import io.swagger.client.model.PublicIdentityDto;
import io.swagger.v3.oas.annotations.media.Schema;
import org.joda.time.DateTime;
/**
 * EnvironnementDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-04T22:32:11.845Z[GMT]")
public class EnvironnementDto {
  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDate")
  private DateTime createdDate = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDate")
  private DateTime lastModifiedDate = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("host")
  private String host = null;

  @JsonProperty("identity")
  private PublicIdentityDto identity = null;

  @JsonProperty("homePath")
  private String homePath = null;

  @JsonProperty("prefix")
  private String prefix = null;

  @JsonProperty("diskSpace")
  private Float diskSpace = null;

  @JsonProperty("dateTraitement")
  private DateTime dateTraitement = null;

  @JsonProperty("norme")
  private NormeDto norme = null;

  public EnvironnementDto createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @Schema(required = true, description = "")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public EnvironnementDto createdDate(DateTime createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @Schema(required = true, description = "")
  public DateTime getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(DateTime createdDate) {
    this.createdDate = createdDate;
  }

  public EnvironnementDto lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  @Schema(description = "")
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public EnvironnementDto lastModifiedDate(DateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
    return this;
  }

   /**
   * Get lastModifiedDate
   * @return lastModifiedDate
  **/
  @Schema(description = "")
  public DateTime getLastModifiedDate() {
    return lastModifiedDate;
  }

  public void setLastModifiedDate(DateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }

  public EnvironnementDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public EnvironnementDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public EnvironnementDto host(String host) {
    this.host = host;
    return this;
  }

   /**
   * Get host
   * @return host
  **/
  @Schema(description = "")
  public String getHost() {
    return host;
  }

  public void setHost(String host) {
    this.host = host;
  }

  public EnvironnementDto identity(PublicIdentityDto identity) {
    this.identity = identity;
    return this;
  }

   /**
   * Get identity
   * @return identity
  **/
  @Schema(description = "")
  public PublicIdentityDto getIdentity() {
    return identity;
  }

  public void setIdentity(PublicIdentityDto identity) {
    this.identity = identity;
  }

  public EnvironnementDto homePath(String homePath) {
    this.homePath = homePath;
    return this;
  }

   /**
   * Get homePath
   * @return homePath
  **/
  @Schema(description = "")
  public String getHomePath() {
    return homePath;
  }

  public void setHomePath(String homePath) {
    this.homePath = homePath;
  }

  public EnvironnementDto prefix(String prefix) {
    this.prefix = prefix;
    return this;
  }

   /**
   * Get prefix
   * @return prefix
  **/
  @Schema(description = "")
  public String getPrefix() {
    return prefix;
  }

  public void setPrefix(String prefix) {
    this.prefix = prefix;
  }

  public EnvironnementDto diskSpace(Float diskSpace) {
    this.diskSpace = diskSpace;
    return this;
  }

   /**
   * Get diskSpace
   * @return diskSpace
  **/
  @Schema(description = "")
  public Float getDiskSpace() {
    return diskSpace;
  }

  public void setDiskSpace(Float diskSpace) {
    this.diskSpace = diskSpace;
  }

  public EnvironnementDto dateTraitement(DateTime dateTraitement) {
    this.dateTraitement = dateTraitement;
    return this;
  }

   /**
   * Get dateTraitement
   * @return dateTraitement
  **/
  @Schema(description = "")
  public DateTime getDateTraitement() {
    return dateTraitement;
  }

  public void setDateTraitement(DateTime dateTraitement) {
    this.dateTraitement = dateTraitement;
  }

  public EnvironnementDto norme(NormeDto norme) {
    this.norme = norme;
    return this;
  }

   /**
   * Get norme
   * @return norme
  **/
  @Schema(description = "")
  public NormeDto getNorme() {
    return norme;
  }

  public void setNorme(NormeDto norme) {
    this.norme = norme;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnvironnementDto environnementDto = (EnvironnementDto) o;
    return Objects.equals(this.createdBy, environnementDto.createdBy) &&
        Objects.equals(this.createdDate, environnementDto.createdDate) &&
        Objects.equals(this.lastModifiedBy, environnementDto.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDate, environnementDto.lastModifiedDate) &&
        Objects.equals(this.id, environnementDto.id) &&
        Objects.equals(this.name, environnementDto.name) &&
        Objects.equals(this.host, environnementDto.host) &&
        Objects.equals(this.identity, environnementDto.identity) &&
        Objects.equals(this.homePath, environnementDto.homePath) &&
        Objects.equals(this.prefix, environnementDto.prefix) &&
        Objects.equals(this.diskSpace, environnementDto.diskSpace) &&
        Objects.equals(this.dateTraitement, environnementDto.dateTraitement) &&
        Objects.equals(this.norme, environnementDto.norme);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdBy, createdDate, lastModifiedBy, lastModifiedDate, id, name, host, identity, homePath, prefix, diskSpace, dateTraitement, norme);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnvironnementDto {\n");
    
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDate: ").append(toIndentedString(lastModifiedDate)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    identity: ").append(toIndentedString(identity)).append("\n");
    sb.append("    homePath: ").append(toIndentedString(homePath)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    diskSpace: ").append(toIndentedString(diskSpace)).append("\n");
    sb.append("    dateTraitement: ").append(toIndentedString(dateTraitement)).append("\n");
    sb.append("    norme: ").append(toIndentedString(norme)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
