/*
 * EBAD API
 * This documentation describe EBAD API.
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.client.model.ApplicationDto;
import io.swagger.client.model.NormeDto;
import io.swagger.client.model.PublicIdentityDto;
import io.swagger.v3.oas.annotations.media.Schema;
import org.joda.time.DateTime;
/**
 * EnvironnementCreationDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-11T21:08:45.148Z[GMT]")
public class EnvironnementCreationDto {
  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDate")
  private DateTime createdDate = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDate")
  private DateTime lastModifiedDate = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("application")
  private ApplicationDto application = null;

  @JsonProperty("host")
  private String host = null;

  @JsonProperty("identity")
  private PublicIdentityDto identity = null;

  @JsonProperty("homePath")
  private String homePath = null;

  @JsonProperty("prefix")
  private String prefix = null;

  @JsonProperty("norme")
  private NormeDto norme = null;

  public EnvironnementCreationDto createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @Schema(required = true, description = "")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public EnvironnementCreationDto createdDate(DateTime createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @Schema(required = true, description = "")
  public DateTime getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(DateTime createdDate) {
    this.createdDate = createdDate;
  }

  public EnvironnementCreationDto lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  @Schema(description = "")
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public EnvironnementCreationDto lastModifiedDate(DateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
    return this;
  }

   /**
   * Get lastModifiedDate
   * @return lastModifiedDate
  **/
  @Schema(description = "")
  public DateTime getLastModifiedDate() {
    return lastModifiedDate;
  }

  public void setLastModifiedDate(DateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }

  public EnvironnementCreationDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public EnvironnementCreationDto application(ApplicationDto application) {
    this.application = application;
    return this;
  }

   /**
   * Get application
   * @return application
  **/
  @Schema(description = "")
  public ApplicationDto getApplication() {
    return application;
  }

  public void setApplication(ApplicationDto application) {
    this.application = application;
  }

  public EnvironnementCreationDto host(String host) {
    this.host = host;
    return this;
  }

   /**
   * Get host
   * @return host
  **/
  @Schema(description = "")
  public String getHost() {
    return host;
  }

  public void setHost(String host) {
    this.host = host;
  }

  public EnvironnementCreationDto identity(PublicIdentityDto identity) {
    this.identity = identity;
    return this;
  }

   /**
   * Get identity
   * @return identity
  **/
  @Schema(description = "")
  public PublicIdentityDto getIdentity() {
    return identity;
  }

  public void setIdentity(PublicIdentityDto identity) {
    this.identity = identity;
  }

  public EnvironnementCreationDto homePath(String homePath) {
    this.homePath = homePath;
    return this;
  }

   /**
   * Get homePath
   * @return homePath
  **/
  @Schema(description = "")
  public String getHomePath() {
    return homePath;
  }

  public void setHomePath(String homePath) {
    this.homePath = homePath;
  }

  public EnvironnementCreationDto prefix(String prefix) {
    this.prefix = prefix;
    return this;
  }

   /**
   * Get prefix
   * @return prefix
  **/
  @Schema(description = "")
  public String getPrefix() {
    return prefix;
  }

  public void setPrefix(String prefix) {
    this.prefix = prefix;
  }

  public EnvironnementCreationDto norme(NormeDto norme) {
    this.norme = norme;
    return this;
  }

   /**
   * Get norme
   * @return norme
  **/
  @Schema(description = "")
  public NormeDto getNorme() {
    return norme;
  }

  public void setNorme(NormeDto norme) {
    this.norme = norme;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnvironnementCreationDto environnementCreationDto = (EnvironnementCreationDto) o;
    return Objects.equals(this.createdBy, environnementCreationDto.createdBy) &&
        Objects.equals(this.createdDate, environnementCreationDto.createdDate) &&
        Objects.equals(this.lastModifiedBy, environnementCreationDto.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDate, environnementCreationDto.lastModifiedDate) &&
        Objects.equals(this.name, environnementCreationDto.name) &&
        Objects.equals(this.application, environnementCreationDto.application) &&
        Objects.equals(this.host, environnementCreationDto.host) &&
        Objects.equals(this.identity, environnementCreationDto.identity) &&
        Objects.equals(this.homePath, environnementCreationDto.homePath) &&
        Objects.equals(this.prefix, environnementCreationDto.prefix) &&
        Objects.equals(this.norme, environnementCreationDto.norme);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdBy, createdDate, lastModifiedBy, lastModifiedDate, name, application, host, identity, homePath, prefix, norme);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnvironnementCreationDto {\n");
    
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDate: ").append(toIndentedString(lastModifiedDate)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    application: ").append(toIndentedString(application)).append("\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    identity: ").append(toIndentedString(identity)).append("\n");
    sb.append("    homePath: ").append(toIndentedString(homePath)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    norme: ").append(toIndentedString(norme)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
