/*
 * EBAD API
 * This documentation describe EBAD API.
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.client.model.Application;
import io.swagger.client.model.Identity;
import io.swagger.client.model.Norme;
import io.swagger.v3.oas.annotations.media.Schema;
import org.joda.time.DateTime;
/**
 * Environnement
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-04T22:32:11.845Z[GMT]")
public class Environnement {
  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDate")
  private DateTime createdDate = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDate")
  private DateTime lastModifiedDate = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("externalId")
  private String externalId = null;

  @JsonProperty("pluginId")
  private String pluginId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("application")
  private Application application = null;

  @JsonProperty("host")
  private String host = null;

  @JsonProperty("identity")
  private Identity identity = null;

  @JsonProperty("homePath")
  private String homePath = null;

  @JsonProperty("prefix")
  private String prefix = null;

  @JsonProperty("diskSpace")
  private Float diskSpace = null;

  @JsonProperty("dateTraitement")
  private DateTime dateTraitement = null;

  @JsonProperty("norme")
  private Norme norme = null;

  public Environnement createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @Schema(required = true, description = "")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public Environnement createdDate(DateTime createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @Schema(required = true, description = "")
  public DateTime getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(DateTime createdDate) {
    this.createdDate = createdDate;
  }

  public Environnement lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  @Schema(description = "")
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public Environnement lastModifiedDate(DateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
    return this;
  }

   /**
   * Get lastModifiedDate
   * @return lastModifiedDate
  **/
  @Schema(description = "")
  public DateTime getLastModifiedDate() {
    return lastModifiedDate;
  }

  public void setLastModifiedDate(DateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }

  public Environnement id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Environnement externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * Get externalId
   * @return externalId
  **/
  @Schema(description = "")
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  public Environnement pluginId(String pluginId) {
    this.pluginId = pluginId;
    return this;
  }

   /**
   * Get pluginId
   * @return pluginId
  **/
  @Schema(description = "")
  public String getPluginId() {
    return pluginId;
  }

  public void setPluginId(String pluginId) {
    this.pluginId = pluginId;
  }

  public Environnement name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Environnement application(Application application) {
    this.application = application;
    return this;
  }

   /**
   * Get application
   * @return application
  **/
  @Schema(required = true, description = "")
  public Application getApplication() {
    return application;
  }

  public void setApplication(Application application) {
    this.application = application;
  }

  public Environnement host(String host) {
    this.host = host;
    return this;
  }

   /**
   * Get host
   * @return host
  **/
  @Schema(required = true, description = "")
  public String getHost() {
    return host;
  }

  public void setHost(String host) {
    this.host = host;
  }

  public Environnement identity(Identity identity) {
    this.identity = identity;
    return this;
  }

   /**
   * Get identity
   * @return identity
  **/
  @Schema(required = true, description = "")
  public Identity getIdentity() {
    return identity;
  }

  public void setIdentity(Identity identity) {
    this.identity = identity;
  }

  public Environnement homePath(String homePath) {
    this.homePath = homePath;
    return this;
  }

   /**
   * Get homePath
   * @return homePath
  **/
  @Schema(description = "")
  public String getHomePath() {
    return homePath;
  }

  public void setHomePath(String homePath) {
    this.homePath = homePath;
  }

  public Environnement prefix(String prefix) {
    this.prefix = prefix;
    return this;
  }

   /**
   * Get prefix
   * @return prefix
  **/
  @Schema(required = true, description = "")
  public String getPrefix() {
    return prefix;
  }

  public void setPrefix(String prefix) {
    this.prefix = prefix;
  }

  public Environnement diskSpace(Float diskSpace) {
    this.diskSpace = diskSpace;
    return this;
  }

   /**
   * Get diskSpace
   * @return diskSpace
  **/
  @Schema(description = "")
  public Float getDiskSpace() {
    return diskSpace;
  }

  public void setDiskSpace(Float diskSpace) {
    this.diskSpace = diskSpace;
  }

  public Environnement dateTraitement(DateTime dateTraitement) {
    this.dateTraitement = dateTraitement;
    return this;
  }

   /**
   * Get dateTraitement
   * @return dateTraitement
  **/
  @Schema(description = "")
  public DateTime getDateTraitement() {
    return dateTraitement;
  }

  public void setDateTraitement(DateTime dateTraitement) {
    this.dateTraitement = dateTraitement;
  }

  public Environnement norme(Norme norme) {
    this.norme = norme;
    return this;
  }

   /**
   * Get norme
   * @return norme
  **/
  @Schema(required = true, description = "")
  public Norme getNorme() {
    return norme;
  }

  public void setNorme(Norme norme) {
    this.norme = norme;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Environnement environnement = (Environnement) o;
    return Objects.equals(this.createdBy, environnement.createdBy) &&
        Objects.equals(this.createdDate, environnement.createdDate) &&
        Objects.equals(this.lastModifiedBy, environnement.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDate, environnement.lastModifiedDate) &&
        Objects.equals(this.id, environnement.id) &&
        Objects.equals(this.externalId, environnement.externalId) &&
        Objects.equals(this.pluginId, environnement.pluginId) &&
        Objects.equals(this.name, environnement.name) &&
        Objects.equals(this.application, environnement.application) &&
        Objects.equals(this.host, environnement.host) &&
        Objects.equals(this.identity, environnement.identity) &&
        Objects.equals(this.homePath, environnement.homePath) &&
        Objects.equals(this.prefix, environnement.prefix) &&
        Objects.equals(this.diskSpace, environnement.diskSpace) &&
        Objects.equals(this.dateTraitement, environnement.dateTraitement) &&
        Objects.equals(this.norme, environnement.norme);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdBy, createdDate, lastModifiedBy, lastModifiedDate, id, externalId, pluginId, name, application, host, identity, homePath, prefix, diskSpace, dateTraitement, norme);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Environnement {\n");
    
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDate: ").append(toIndentedString(lastModifiedDate)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    pluginId: ").append(toIndentedString(pluginId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    application: ").append(toIndentedString(application)).append("\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    identity: ").append(toIndentedString(identity)).append("\n");
    sb.append("    homePath: ").append(toIndentedString(homePath)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    diskSpace: ").append(toIndentedString(diskSpace)).append("\n");
    sb.append("    dateTraitement: ").append(toIndentedString(dateTraitement)).append("\n");
    sb.append("    norme: ").append(toIndentedString(norme)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
