/*
 * EBAD API
 * This documentation describe EBAD API.
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.client.model.DirectoryDto;
import io.swagger.v3.oas.annotations.media.Schema;
import org.joda.time.DateTime;
/**
 * FilesDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-11T21:08:45.148Z[GMT]")
public class FilesDto {
  @JsonProperty("directory")
  private DirectoryDto directory = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("size")
  private Long size = null;

  @JsonProperty("updateDate")
  private DateTime updateDate = null;

  @JsonProperty("createDate")
  private DateTime createDate = null;

  @JsonProperty("subDirectory")
  private String subDirectory = null;

  @JsonProperty("folder")
  private Boolean folder = null;

  public FilesDto directory(DirectoryDto directory) {
    this.directory = directory;
    return this;
  }

   /**
   * Get directory
   * @return directory
  **/
  @Schema(description = "")
  public DirectoryDto getDirectory() {
    return directory;
  }

  public void setDirectory(DirectoryDto directory) {
    this.directory = directory;
  }

  public FilesDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public FilesDto size(Long size) {
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @Schema(description = "")
  public Long getSize() {
    return size;
  }

  public void setSize(Long size) {
    this.size = size;
  }

  public FilesDto updateDate(DateTime updateDate) {
    this.updateDate = updateDate;
    return this;
  }

   /**
   * Get updateDate
   * @return updateDate
  **/
  @Schema(description = "")
  public DateTime getUpdateDate() {
    return updateDate;
  }

  public void setUpdateDate(DateTime updateDate) {
    this.updateDate = updateDate;
  }

  public FilesDto createDate(DateTime createDate) {
    this.createDate = createDate;
    return this;
  }

   /**
   * Get createDate
   * @return createDate
  **/
  @Schema(description = "")
  public DateTime getCreateDate() {
    return createDate;
  }

  public void setCreateDate(DateTime createDate) {
    this.createDate = createDate;
  }

  public FilesDto subDirectory(String subDirectory) {
    this.subDirectory = subDirectory;
    return this;
  }

   /**
   * Get subDirectory
   * @return subDirectory
  **/
  @Schema(description = "")
  public String getSubDirectory() {
    return subDirectory;
  }

  public void setSubDirectory(String subDirectory) {
    this.subDirectory = subDirectory;
  }

  public FilesDto folder(Boolean folder) {
    this.folder = folder;
    return this;
  }

   /**
   * Get folder
   * @return folder
  **/
  @Schema(description = "")
  public Boolean isFolder() {
    return folder;
  }

  public void setFolder(Boolean folder) {
    this.folder = folder;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FilesDto filesDto = (FilesDto) o;
    return Objects.equals(this.directory, filesDto.directory) &&
        Objects.equals(this.name, filesDto.name) &&
        Objects.equals(this.size, filesDto.size) &&
        Objects.equals(this.updateDate, filesDto.updateDate) &&
        Objects.equals(this.createDate, filesDto.createDate) &&
        Objects.equals(this.subDirectory, filesDto.subDirectory) &&
        Objects.equals(this.folder, filesDto.folder);
  }

  @Override
  public int hashCode() {
    return Objects.hash(directory, name, size, updateDate, createDate, subDirectory, folder);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FilesDto {\n");
    
    sb.append("    directory: ").append(toIndentedString(directory)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    updateDate: ").append(toIndentedString(updateDate)).append("\n");
    sb.append("    createDate: ").append(toIndentedString(createDate)).append("\n");
    sb.append("    subDirectory: ").append(toIndentedString(subDirectory)).append("\n");
    sb.append("    folder: ").append(toIndentedString(folder)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
