/*
 * EBAD API
 * This documentation describe EBAD API.
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.client.model.BatchLogDto;
import io.swagger.client.model.EnvironnementDto;
import io.swagger.v3.oas.annotations.media.Schema;
import org.joda.time.DateTime;
/**
 * LogBatchDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-04T22:32:11.845Z[GMT]")
public class LogBatchDto {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("batch")
  private BatchLogDto batch = null;

  @JsonProperty("environnement")
  private EnvironnementDto environnement = null;

  @JsonProperty("logDate")
  private DateTime logDate = null;

  @JsonProperty("executionTime")
  private Long executionTime = null;

  @JsonProperty("returnCode")
  private Integer returnCode = null;

  @JsonProperty("params")
  private String params = null;

  @JsonProperty("dateTraitement")
  private DateTime dateTraitement = null;

  @JsonProperty("login")
  private String login = null;

  public LogBatchDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public LogBatchDto batch(BatchLogDto batch) {
    this.batch = batch;
    return this;
  }

   /**
   * Get batch
   * @return batch
  **/
  @Schema(description = "")
  public BatchLogDto getBatch() {
    return batch;
  }

  public void setBatch(BatchLogDto batch) {
    this.batch = batch;
  }

  public LogBatchDto environnement(EnvironnementDto environnement) {
    this.environnement = environnement;
    return this;
  }

   /**
   * Get environnement
   * @return environnement
  **/
  @Schema(description = "")
  public EnvironnementDto getEnvironnement() {
    return environnement;
  }

  public void setEnvironnement(EnvironnementDto environnement) {
    this.environnement = environnement;
  }

  public LogBatchDto logDate(DateTime logDate) {
    this.logDate = logDate;
    return this;
  }

   /**
   * Get logDate
   * @return logDate
  **/
  @Schema(description = "")
  public DateTime getLogDate() {
    return logDate;
  }

  public void setLogDate(DateTime logDate) {
    this.logDate = logDate;
  }

  public LogBatchDto executionTime(Long executionTime) {
    this.executionTime = executionTime;
    return this;
  }

   /**
   * Get executionTime
   * @return executionTime
  **/
  @Schema(description = "")
  public Long getExecutionTime() {
    return executionTime;
  }

  public void setExecutionTime(Long executionTime) {
    this.executionTime = executionTime;
  }

  public LogBatchDto returnCode(Integer returnCode) {
    this.returnCode = returnCode;
    return this;
  }

   /**
   * Get returnCode
   * @return returnCode
  **/
  @Schema(description = "")
  public Integer getReturnCode() {
    return returnCode;
  }

  public void setReturnCode(Integer returnCode) {
    this.returnCode = returnCode;
  }

  public LogBatchDto params(String params) {
    this.params = params;
    return this;
  }

   /**
   * Get params
   * @return params
  **/
  @Schema(description = "")
  public String getParams() {
    return params;
  }

  public void setParams(String params) {
    this.params = params;
  }

  public LogBatchDto dateTraitement(DateTime dateTraitement) {
    this.dateTraitement = dateTraitement;
    return this;
  }

   /**
   * Get dateTraitement
   * @return dateTraitement
  **/
  @Schema(description = "")
  public DateTime getDateTraitement() {
    return dateTraitement;
  }

  public void setDateTraitement(DateTime dateTraitement) {
    this.dateTraitement = dateTraitement;
  }

  public LogBatchDto login(String login) {
    this.login = login;
    return this;
  }

   /**
   * Get login
   * @return login
  **/
  @Schema(description = "")
  public String getLogin() {
    return login;
  }

  public void setLogin(String login) {
    this.login = login;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LogBatchDto logBatchDto = (LogBatchDto) o;
    return Objects.equals(this.id, logBatchDto.id) &&
        Objects.equals(this.batch, logBatchDto.batch) &&
        Objects.equals(this.environnement, logBatchDto.environnement) &&
        Objects.equals(this.logDate, logBatchDto.logDate) &&
        Objects.equals(this.executionTime, logBatchDto.executionTime) &&
        Objects.equals(this.returnCode, logBatchDto.returnCode) &&
        Objects.equals(this.params, logBatchDto.params) &&
        Objects.equals(this.dateTraitement, logBatchDto.dateTraitement) &&
        Objects.equals(this.login, logBatchDto.login);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, batch, environnement, logDate, executionTime, returnCode, params, dateTraitement, login);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LogBatchDto {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    batch: ").append(toIndentedString(batch)).append("\n");
    sb.append("    environnement: ").append(toIndentedString(environnement)).append("\n");
    sb.append("    logDate: ").append(toIndentedString(logDate)).append("\n");
    sb.append("    executionTime: ").append(toIndentedString(executionTime)).append("\n");
    sb.append("    returnCode: ").append(toIndentedString(returnCode)).append("\n");
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("    dateTraitement: ").append(toIndentedString(dateTraitement)).append("\n");
    sb.append("    login: ").append(toIndentedString(login)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
