/*
 * EBAD API
 * This documentation describe EBAD API.
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import org.joda.time.DateTime;
/**
 * NormeDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-10T21:22:29.539Z[GMT]")
public class NormeDto {
  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDate")
  private DateTime createdDate = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDate")
  private DateTime lastModifiedDate = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("code")
  private String code = null;

  @JsonProperty("dateFichierPattern")
  private String dateFichierPattern = null;

  @JsonProperty("dateParametrePattern")
  private String dateParametrePattern = null;

  @JsonProperty("commandLine")
  private String commandLine = null;

  @JsonProperty("pathShell")
  private String pathShell = null;

  @JsonProperty("ctrlMDate")
  private String ctrlMDate = null;

  public NormeDto createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @Schema(description = "")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public NormeDto createdDate(DateTime createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @Schema(description = "")
  public DateTime getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(DateTime createdDate) {
    this.createdDate = createdDate;
  }

  public NormeDto lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  @Schema(description = "")
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public NormeDto lastModifiedDate(DateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
    return this;
  }

   /**
   * Get lastModifiedDate
   * @return lastModifiedDate
  **/
  @Schema(description = "")
  public DateTime getLastModifiedDate() {
    return lastModifiedDate;
  }

  public void setLastModifiedDate(DateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }

  public NormeDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public NormeDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public NormeDto code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @Schema(description = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public NormeDto dateFichierPattern(String dateFichierPattern) {
    this.dateFichierPattern = dateFichierPattern;
    return this;
  }

   /**
   * Get dateFichierPattern
   * @return dateFichierPattern
  **/
  @Schema(description = "")
  public String getDateFichierPattern() {
    return dateFichierPattern;
  }

  public void setDateFichierPattern(String dateFichierPattern) {
    this.dateFichierPattern = dateFichierPattern;
  }

  public NormeDto dateParametrePattern(String dateParametrePattern) {
    this.dateParametrePattern = dateParametrePattern;
    return this;
  }

   /**
   * Get dateParametrePattern
   * @return dateParametrePattern
  **/
  @Schema(description = "")
  public String getDateParametrePattern() {
    return dateParametrePattern;
  }

  public void setDateParametrePattern(String dateParametrePattern) {
    this.dateParametrePattern = dateParametrePattern;
  }

  public NormeDto commandLine(String commandLine) {
    this.commandLine = commandLine;
    return this;
  }

   /**
   * Get commandLine
   * @return commandLine
  **/
  @Schema(description = "")
  public String getCommandLine() {
    return commandLine;
  }

  public void setCommandLine(String commandLine) {
    this.commandLine = commandLine;
  }

  public NormeDto pathShell(String pathShell) {
    this.pathShell = pathShell;
    return this;
  }

   /**
   * Get pathShell
   * @return pathShell
  **/
  @Schema(description = "")
  public String getPathShell() {
    return pathShell;
  }

  public void setPathShell(String pathShell) {
    this.pathShell = pathShell;
  }

  public NormeDto ctrlMDate(String ctrlMDate) {
    this.ctrlMDate = ctrlMDate;
    return this;
  }

   /**
   * Get ctrlMDate
   * @return ctrlMDate
  **/
  @Schema(description = "")
  public String getCtrlMDate() {
    return ctrlMDate;
  }

  public void setCtrlMDate(String ctrlMDate) {
    this.ctrlMDate = ctrlMDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NormeDto normeDto = (NormeDto) o;
    return Objects.equals(this.createdBy, normeDto.createdBy) &&
        Objects.equals(this.createdDate, normeDto.createdDate) &&
        Objects.equals(this.lastModifiedBy, normeDto.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDate, normeDto.lastModifiedDate) &&
        Objects.equals(this.id, normeDto.id) &&
        Objects.equals(this.name, normeDto.name) &&
        Objects.equals(this.code, normeDto.code) &&
        Objects.equals(this.dateFichierPattern, normeDto.dateFichierPattern) &&
        Objects.equals(this.dateParametrePattern, normeDto.dateParametrePattern) &&
        Objects.equals(this.commandLine, normeDto.commandLine) &&
        Objects.equals(this.pathShell, normeDto.pathShell) &&
        Objects.equals(this.ctrlMDate, normeDto.ctrlMDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdBy, createdDate, lastModifiedBy, lastModifiedDate, id, name, code, dateFichierPattern, dateParametrePattern, commandLine, pathShell, ctrlMDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NormeDto {\n");
    
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDate: ").append(toIndentedString(lastModifiedDate)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    dateFichierPattern: ").append(toIndentedString(dateFichierPattern)).append("\n");
    sb.append("    dateParametrePattern: ").append(toIndentedString(dateParametrePattern)).append("\n");
    sb.append("    commandLine: ").append(toIndentedString(commandLine)).append("\n");
    sb.append("    pathShell: ").append(toIndentedString(pathShell)).append("\n");
    sb.append("    ctrlMDate: ").append(toIndentedString(ctrlMDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
