/*
 * EBAD API
 * This documentation describe EBAD API.
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * RolesDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-10T21:22:29.539Z[GMT]")
public class RolesDTO {
  @JsonProperty("loginUser")
  private String loginUser = null;

  @JsonProperty("roleUser")
  private Boolean roleUser = null;

  @JsonProperty("roleAdmin")
  private Boolean roleAdmin = null;

  public RolesDTO loginUser(String loginUser) {
    this.loginUser = loginUser;
    return this;
  }

   /**
   * Get loginUser
   * @return loginUser
  **/
  @Schema(description = "")
  public String getLoginUser() {
    return loginUser;
  }

  public void setLoginUser(String loginUser) {
    this.loginUser = loginUser;
  }

  public RolesDTO roleUser(Boolean roleUser) {
    this.roleUser = roleUser;
    return this;
  }

   /**
   * Get roleUser
   * @return roleUser
  **/
  @Schema(description = "")
  public Boolean isRoleUser() {
    return roleUser;
  }

  public void setRoleUser(Boolean roleUser) {
    this.roleUser = roleUser;
  }

  public RolesDTO roleAdmin(Boolean roleAdmin) {
    this.roleAdmin = roleAdmin;
    return this;
  }

   /**
   * Get roleAdmin
   * @return roleAdmin
  **/
  @Schema(description = "")
  public Boolean isRoleAdmin() {
    return roleAdmin;
  }

  public void setRoleAdmin(Boolean roleAdmin) {
    this.roleAdmin = roleAdmin;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RolesDTO rolesDTO = (RolesDTO) o;
    return Objects.equals(this.loginUser, rolesDTO.loginUser) &&
        Objects.equals(this.roleUser, rolesDTO.roleUser) &&
        Objects.equals(this.roleAdmin, rolesDTO.roleAdmin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loginUser, roleUser, roleAdmin);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RolesDTO {\n");
    
    sb.append("    loginUser: ").append(toIndentedString(loginUser)).append("\n");
    sb.append("    roleUser: ").append(toIndentedString(roleUser)).append("\n");
    sb.append("    roleAdmin: ").append(toIndentedString(roleAdmin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
