/*
 * EBAD API
 * This documentation describe EBAD API.
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * StatisticByDayDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-04T22:32:11.845Z[GMT]")
public class StatisticByDayDto {
  @JsonProperty("date")
  private String date = null;

  @JsonProperty("nbr")
  private Long nbr = null;

  @JsonProperty("executionTime")
  private Double executionTime = null;

  public StatisticByDayDto date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @Schema(description = "")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public StatisticByDayDto nbr(Long nbr) {
    this.nbr = nbr;
    return this;
  }

   /**
   * Get nbr
   * @return nbr
  **/
  @Schema(description = "")
  public Long getNbr() {
    return nbr;
  }

  public void setNbr(Long nbr) {
    this.nbr = nbr;
  }

  public StatisticByDayDto executionTime(Double executionTime) {
    this.executionTime = executionTime;
    return this;
  }

   /**
   * Get executionTime
   * @return executionTime
  **/
  @Schema(description = "")
  public Double getExecutionTime() {
    return executionTime;
  }

  public void setExecutionTime(Double executionTime) {
    this.executionTime = executionTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatisticByDayDto statisticByDayDto = (StatisticByDayDto) o;
    return Objects.equals(this.date, statisticByDayDto.date) &&
        Objects.equals(this.nbr, statisticByDayDto.nbr) &&
        Objects.equals(this.executionTime, statisticByDayDto.executionTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, nbr, executionTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatisticByDayDto {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    nbr: ").append(toIndentedString(nbr)).append("\n");
    sb.append("    executionTime: ").append(toIndentedString(executionTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
