/*
 * EBAD API
 * This documentation describe EBAD API.
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.client.model.StatisticByDayDto;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * StatisticsDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-11T21:08:45.148Z[GMT]")
public class StatisticsDto {
  @JsonProperty("usersNbr")
  private Long usersNbr = null;

  @JsonProperty("batchsRunnedNbrs")
  private Long batchsRunnedNbrs = null;

  @JsonProperty("avgExecutionTime")
  private Long avgExecutionTime = null;

  @JsonProperty("batchsNbrs")
  private Long batchsNbrs = null;

  @JsonProperty("applicationsNbr")
  private Long applicationsNbr = null;

  @JsonProperty("statisticsByDay")
  private List<StatisticByDayDto> statisticsByDay = null;

  public StatisticsDto usersNbr(Long usersNbr) {
    this.usersNbr = usersNbr;
    return this;
  }

   /**
   * Get usersNbr
   * @return usersNbr
  **/
  @Schema(description = "")
  public Long getUsersNbr() {
    return usersNbr;
  }

  public void setUsersNbr(Long usersNbr) {
    this.usersNbr = usersNbr;
  }

  public StatisticsDto batchsRunnedNbrs(Long batchsRunnedNbrs) {
    this.batchsRunnedNbrs = batchsRunnedNbrs;
    return this;
  }

   /**
   * Get batchsRunnedNbrs
   * @return batchsRunnedNbrs
  **/
  @Schema(description = "")
  public Long getBatchsRunnedNbrs() {
    return batchsRunnedNbrs;
  }

  public void setBatchsRunnedNbrs(Long batchsRunnedNbrs) {
    this.batchsRunnedNbrs = batchsRunnedNbrs;
  }

  public StatisticsDto avgExecutionTime(Long avgExecutionTime) {
    this.avgExecutionTime = avgExecutionTime;
    return this;
  }

   /**
   * Get avgExecutionTime
   * @return avgExecutionTime
  **/
  @Schema(description = "")
  public Long getAvgExecutionTime() {
    return avgExecutionTime;
  }

  public void setAvgExecutionTime(Long avgExecutionTime) {
    this.avgExecutionTime = avgExecutionTime;
  }

  public StatisticsDto batchsNbrs(Long batchsNbrs) {
    this.batchsNbrs = batchsNbrs;
    return this;
  }

   /**
   * Get batchsNbrs
   * @return batchsNbrs
  **/
  @Schema(description = "")
  public Long getBatchsNbrs() {
    return batchsNbrs;
  }

  public void setBatchsNbrs(Long batchsNbrs) {
    this.batchsNbrs = batchsNbrs;
  }

  public StatisticsDto applicationsNbr(Long applicationsNbr) {
    this.applicationsNbr = applicationsNbr;
    return this;
  }

   /**
   * Get applicationsNbr
   * @return applicationsNbr
  **/
  @Schema(description = "")
  public Long getApplicationsNbr() {
    return applicationsNbr;
  }

  public void setApplicationsNbr(Long applicationsNbr) {
    this.applicationsNbr = applicationsNbr;
  }

  public StatisticsDto statisticsByDay(List<StatisticByDayDto> statisticsByDay) {
    this.statisticsByDay = statisticsByDay;
    return this;
  }

  public StatisticsDto addStatisticsByDayItem(StatisticByDayDto statisticsByDayItem) {
    if (this.statisticsByDay == null) {
      this.statisticsByDay = new ArrayList<StatisticByDayDto>();
    }
    this.statisticsByDay.add(statisticsByDayItem);
    return this;
  }

   /**
   * Get statisticsByDay
   * @return statisticsByDay
  **/
  @Schema(description = "")
  public List<StatisticByDayDto> getStatisticsByDay() {
    return statisticsByDay;
  }

  public void setStatisticsByDay(List<StatisticByDayDto> statisticsByDay) {
    this.statisticsByDay = statisticsByDay;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatisticsDto statisticsDto = (StatisticsDto) o;
    return Objects.equals(this.usersNbr, statisticsDto.usersNbr) &&
        Objects.equals(this.batchsRunnedNbrs, statisticsDto.batchsRunnedNbrs) &&
        Objects.equals(this.avgExecutionTime, statisticsDto.avgExecutionTime) &&
        Objects.equals(this.batchsNbrs, statisticsDto.batchsNbrs) &&
        Objects.equals(this.applicationsNbr, statisticsDto.applicationsNbr) &&
        Objects.equals(this.statisticsByDay, statisticsDto.statisticsByDay);
  }

  @Override
  public int hashCode() {
    return Objects.hash(usersNbr, batchsRunnedNbrs, avgExecutionTime, batchsNbrs, applicationsNbr, statisticsByDay);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatisticsDto {\n");
    
    sb.append("    usersNbr: ").append(toIndentedString(usersNbr)).append("\n");
    sb.append("    batchsRunnedNbrs: ").append(toIndentedString(batchsRunnedNbrs)).append("\n");
    sb.append("    avgExecutionTime: ").append(toIndentedString(avgExecutionTime)).append("\n");
    sb.append("    batchsNbrs: ").append(toIndentedString(batchsNbrs)).append("\n");
    sb.append("    applicationsNbr: ").append(toIndentedString(applicationsNbr)).append("\n");
    sb.append("    statisticsByDay: ").append(toIndentedString(statisticsByDay)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
