/*
 * EBAD API
 * This documentation describe EBAD API.
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * UsageApplicationSimpleDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-10T21:22:29.539Z[GMT]")
public class UsageApplicationSimpleDto {
  @JsonProperty("applicationId")
  private Long applicationId = null;

  @JsonProperty("canManage")
  private Boolean canManage = null;

  @JsonProperty("canUse")
  private Boolean canUse = null;

  public UsageApplicationSimpleDto applicationId(Long applicationId) {
    this.applicationId = applicationId;
    return this;
  }

   /**
   * Get applicationId
   * @return applicationId
  **/
  @Schema(description = "")
  public Long getApplicationId() {
    return applicationId;
  }

  public void setApplicationId(Long applicationId) {
    this.applicationId = applicationId;
  }

  public UsageApplicationSimpleDto canManage(Boolean canManage) {
    this.canManage = canManage;
    return this;
  }

   /**
   * Get canManage
   * @return canManage
  **/
  @Schema(description = "")
  public Boolean isCanManage() {
    return canManage;
  }

  public void setCanManage(Boolean canManage) {
    this.canManage = canManage;
  }

  public UsageApplicationSimpleDto canUse(Boolean canUse) {
    this.canUse = canUse;
    return this;
  }

   /**
   * Get canUse
   * @return canUse
  **/
  @Schema(description = "")
  public Boolean isCanUse() {
    return canUse;
  }

  public void setCanUse(Boolean canUse) {
    this.canUse = canUse;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsageApplicationSimpleDto usageApplicationSimpleDto = (UsageApplicationSimpleDto) o;
    return Objects.equals(this.applicationId, usageApplicationSimpleDto.applicationId) &&
        Objects.equals(this.canManage, usageApplicationSimpleDto.canManage) &&
        Objects.equals(this.canUse, usageApplicationSimpleDto.canUse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(applicationId, canManage, canUse);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsageApplicationSimpleDto {\n");
    
    sb.append("    applicationId: ").append(toIndentedString(applicationId)).append("\n");
    sb.append("    canManage: ").append(toIndentedString(canManage)).append("\n");
    sb.append("    canUse: ").append(toIndentedString(canUse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
