/*
 * EBAD API
 * This documentation describe EBAD API.
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.AccreditationRequestDto;
import io.swagger.client.model.CreationAccreditationRequestDto;
import io.swagger.client.model.PageAccreditationRequestDto;
import io.swagger.client.model.Pageable;
import io.swagger.client.model.ResponseAccreditationRequestDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccreditationRequestApi
 */
@Ignore
public class AccreditationRequestApiTest {

    private final AccreditationRequestApi api = new AccreditationRequestApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void answerRequestTest() {
        ResponseAccreditationRequestDto body = null;
        api.answerRequest(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAccreditationRequestTest() {
        CreationAccreditationRequestDto body = null;
        AccreditationRequestDto response = api.createAccreditationRequest(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllTest() {
        Pageable pageable = null;
        PageAccreditationRequestDto response = api.findAll(pageable);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllMyRequestTest() {
        Pageable pageable = null;
        PageAccreditationRequestDto response = api.findAllMyRequest(pageable);

        // TODO: test validations
    }
}
