/*
 * EBAD API
 * This documentation describe EBAD API.
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.CompleteIdentityDto;
import io.swagger.client.model.PagePublicIdentityDto;
import io.swagger.client.model.Pageable;
import io.swagger.client.model.Predicate;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IdentityApi
 */
@Ignore
public class IdentityApiTest {

    private final IdentityApi api = new IdentityApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addIdentityTest() {
        CompleteIdentityDto body = null;
        CompleteIdentityDto response = api.addIdentity(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteIdentityTest() {
        Long identityId = null;
        api.deleteIdentity(identityId);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllIdentitiesTest() {
        Long applicationId = null;
        Predicate predicate = null;
        Pageable pageable = null;
        PagePublicIdentityDto response = api.getAllIdentities(applicationId, predicate, pageable);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOneIdentityTest() {
        Long id = null;
        CompleteIdentityDto response = api.getOneIdentity(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateIdentityTest() {
        CompleteIdentityDto body = null;
        CompleteIdentityDto response = api.updateIdentity(body);

        // TODO: test validations
    }
}
