/*
 * EBAD API
 * This documentation describe EBAD API.
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.PageLogBatchDto;
import io.swagger.client.model.Pageable;
import io.swagger.client.model.Predicate;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LogApi
 */
@Ignore
public class LogApiTest {

    private final LogApi api = new LogApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllLogTest() {
        Predicate predicate = null;
        Pageable pageable = null;
        PageLogBatchDto response = api.getAllLog(predicate, pageable);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllLogFromEnvTest() {
        Long env = null;
        Predicate predicate = null;
        Pageable pageable = null;
        PageLogBatchDto response = api.getAllLogFromEnv(env, predicate, pageable);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllLogFromEnvBatchTest() {
        Long env = null;
        Long batch = null;
        Predicate predicate = null;
        Pageable pageable = null;
        PageLogBatchDto response = api.getAllLogFromEnvBatch(env, batch, predicate, pageable);

        // TODO: test validations
    }
}
