/*
 * EBAD API
 * This documentation describe EBAD API.
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.NormeDto;
import io.swagger.client.model.PageNormLabelIdDto;
import io.swagger.client.model.PageNormeDto;
import io.swagger.client.model.Pageable;
import io.swagger.client.model.Predicate;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NormsApi
 */
@Ignore
public class NormsApiTest {

    private final NormsApi api = new NormsApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void delete1Test() {
        Long id = null;
        api.delete1(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAll1Test() {
        Pageable pageable = null;
        Predicate predicate = null;
        PageNormeDto response = api.getAll1(pageable, predicate);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllForListTest() {
        Pageable pageable = null;
        Predicate predicate = null;
        PageNormLabelIdDto response = api.getAllForList(pageable, predicate);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOneTest() {
        Long id = null;
        NormeDto response = api.getOne(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void saveTest() {
        NormeDto body = null;
        NormeDto response = api.save(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTest() {
        NormeDto body = null;
        NormeDto response = api.update(body);

        // TODO: test validations
    }
}
