/*
 * EBAD API
 * This documentation describe EBAD API.
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.PageTypeFichierDto;
import io.swagger.client.model.Pageable;
import io.swagger.client.model.Predicate;
import io.swagger.client.model.TypeFichierDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TypeFichierApi
 */
@Ignore
public class TypeFichierApiTest {

    private final TypeFichierApi api = new TypeFichierApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addTypeFichierTest() {
        TypeFichierDto body = null;
        TypeFichierDto response = api.addTypeFichier(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllFromEnvTest() {
        Pageable pageable = null;
        Predicate predicate = null;
        Long app = null;
        PageTypeFichierDto response = api.getAllFromEnv(pageable, predicate, app);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeTypeFichierTest() {
        TypeFichierDto body = null;
        api.removeTypeFichier(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTypeFichierTest() {
        TypeFichierDto body = null;
        TypeFichierDto response = api.updateTypeFichier(body);

        // TODO: test validations
    }
}
